services:
  app:
    build: ./src
    container_name: apache
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    depends_on:
      - db
      - redis
    networks:
      - laravel-net
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-net
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    networks:
      - laravel-net
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
networks:
  laravel-net: