services:
  app:
    build:
      context: ./src
    container_name: apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8000"
      - "5173:5173"
    command: /bin/sh -c "npm install && (npm run dev -- --host &) && php artisan serve --host=0.0.0.0 --port=8000"