services:
  app:
    build:
      context: ./src
    container_name: apache
    volumes:
      - ./src:/var/www/html
      - ./docker-entrypoint-dev.sh:/docker-entrypoint.sh
    ports:
      - "8080:8000"
      - "5173:5173"
    entrypoint: /docker-entrypoint.sh